# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def shared_pods
    # Pods for Companies
    # Debugging
    pod 'SwiftLint'
    pod 'SwiftyGif'
    pod 'Nuke-FLAnimatedImage-Plugin'
end

target 'Drinks' do
    # Shared pods
    shared_pods
end

target 'DrinksTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'DrinksUITests' do
    inherit! :search_paths
    # Pods for testing
end

